# Generated by Django 5.0.5 on 2024-05-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_bookcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoption',
            name='can',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], max_length=100),
        ),
    ]
