# Generated by Django 5.0.5 on 2024-05-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='buyer',
        ),
    ]
